version: "3"

services:
  go:
    build: ./go
    tty: true
    volumes:
      - ./go:/go/src
    ports:
      - 3000:3000

  db:
    image: postgres:14.0-alpine
    container_name: postgres-db
    ports:
      - 5432:5432
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    restart: always